### ISSUE TITLE
Pyrough.py sample_class.make_box and make_stl still look for param.H instead of param.eta

### ISSUE THREAD

**Issue by jcappola** [jamodeo12/Pyrough#3]
Hi Dr. Amodeo, 

In the last version update, `H` was changed to `eta` in most places, however, this was missed in Pyrough.py. Cloning the current master, installing, and trying to run any example causes the following error (example on box.json):

```
Traceback (most recent call last):
  File "/home/jcappola/code/Pyrough/Pyrough.py", line 78, in <module>
    param.H,
AttributeError: 'Parameter' object has no attribute 'H'
```

Simple fix on lines 41 and 78 in Pyrough.py just changing `H` to `eta`.

**Comment by jamodeo12** [comment]
Hi, 

Yes, I forgot to push Pyrough.py file. It's done. Problem solved. 

Best regards, 

J.

**Comment by jamodeo12** [comment]
Thank you for reporting the error, the problem has now been solved.

**Comment by jamodeo12** [comment]
Thank you Jonathan !
I forget to pushed the Pyrough.py file, it’s now solved.
Don’t hesitate to contact if need any help with Pyrough.

Best regards,

Dr. Jonathan AMODEO
CNRS researcher

IM2NP lab. UMR 7334 CNRS Univ. Aix-Marseille
Campus de St Jérôme, avenue Escadrille Normandie Niemen
13397 Marseille Cedex 20
+33 7 50 98 10 83 - ***@***.***
my webpage: https://sites.google.com/site/jonathanamodeoresearch/
